name: github action workflow

on:
  workflow_call:
    inputs:
      tag_partial_versions:
        description: ''
        required: false
        default: true
        type: boolean

jobs:
  github-action-workflow:
    runs-on: ubuntu-latest
    steps:
      - run: env | sort
      - run: cat ${GITHUB_EVENT_PATH}
      - uses: ptonini-actions/config-git-user@v1
      - uses: actions/checkout@v6

      # Create release ########################################################
      - uses: ptonini-actions/create-release@v1
        with:
          tag_partial_versions: ${{ inputs.tag_partial_versions }}