name: go workflow

on:
  workflow_call:
    inputs:
      app_name:
        description: ''
        default: ${{ github.event.repository.name }}
        required: false
        type: string
      release_please_manifest:
        description: ''
        required: false
        default: ${{ vars.release_please_manifest }}
        type: string
      go_builder_image:
        description: ''
        required: false
        default: ${{ vars.go_builder_image }}
        type: string
      go_main_file:
        description: ''
        required: false
        default: ${{ vars.go_main_file }}
        type: string

jobs:
  go-workflow:
    runs-on: ubuntu-latest
    steps:
      - run: env | sort
      - run: cat ${GITHUB_EVENT_PATH}
      - uses: actions/checkout@v6

      # Extract version from release-please manifest file #####################
      - run: echo "VERSION=$(jq -r '."."' < ${{ inputs.release_please_manifest }})" | tee -a $GITHUB_ENV

      # Compile application and create checksum ###############################
      - run: | 
          mkdir dist
          docker run -v $(pwd):$(pwd) -w $(pwd) ${{ inputs.go_builder_image }} go build -o dist/${{ inputs.app_name }} ${{ inputs.go_main_file }}
          sha256sum dist/${{ inputs.app_name }} > dist/SHA256SUMS

      # Upload artifact to release ############################################
      - run: gh release upload --clobber v${{ env.VERSION }} dist/${{ inputs.app_name }}
        env:
          GH_TOKEN: ${{ github.token }}