name: linter workflow

on:
  workflow_call:

jobs:
  linter-workflow:
    runs-on: ubuntu-latest
    steps:
      - run: env | sort
      - run: cat ${GITHUB_EVENT_PATH}
      - uses: ptonini-actions/config-git-user@v1
      - uses: actions/checkout@v6
        with:
          ref: ${{ github.head_ref }}

      # C# ####################################################################
      - if: github.event.repository.language == 'C#'
        run: (dotnet restore -f --no-cache && dotnet build && dotnet format) || true

      # NodeJS ################################################################
      - if: github.event.repository.language == 'TypeScript'
        run: (yarn && yarn lint && yarn format) || true

      # Go ####################################################################
      - if: github.event.repository.language == 'Go'
        run: go fmt || true

      # Python ################################################################
      - if: github.event.repository.language == 'Python'
        run: (pip3 install ruff && ruff .) || true

      # HCL ###################################################################
      - if: github.event.repository.language == 'HCL'
        run: |
          wget -qO terragrunt https://github.com/gruntwork-io/terragrunt/releases/latest/download/terragrunt_linux_386 && sudo chmod +x terragrunt
          ./terragrunt hclfmt || true
          terraform fmt -recursive || true

      - uses: EndBug/add-and-commit@v9
        with:
          message: "chore: automated linting"