name: paths filter workflow

on:
  workflow_call:
    inputs:
      filter_file:
        description: ''
        default: filters.yaml
        required: false
        type: string
      filters_cmd:
        description: ''
        required: false
        type: string
      release_please_manifest:
        description: ''
        required: false
        default: .release-please-manifest.json
        type: string
    outputs:
      changes:
        description: ''
        value: ${{ jobs.runner.outputs.changes }}

jobs:
  paths-filter-workflow:
    runs-on: ubuntu-latest
    steps:
      - run: env | sort
      - run: cat ${GITHUB_EVENT_PATH}
      - uses: actions/checkout@v6

      # Generate filters ######################################################
      - run: jq -r 'keys | reduce .[] as $i ({}; .[$i] = $i+"/**")' ${{ inputs.release_please_manifest }} > ${{ inputs.filter_file }}
        if: hashFiles(inputs.release_please_manifest)
      - run: ${{ inputs.filters_cmd }} > ${{ inputs.filter_file }}
        if: inputs.filters_cmd

      # Paths-filter action ###################################################
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: ${{ inputs.filter_file }}
      - run: |
          echo '```json' >> $GITHUB_STEP_SUMMARY
          echo '${{ toJson(steps.filter.outputs) }}' >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
    outputs:
      changes: ${{ steps.filter.outputs.changes }}
