name: release please runner

on:
  workflow_call:
    outputs:
      releases_created:
        description: ''
        value: ${{ jobs.runner.outputs.releases_created }}
      paths_released:
        description: ''
        value: ${{ jobs.runner.outputs.paths_released }}


jobs:
  runner:
    runs-on: ubuntu-latest
    steps:
      - run: env | sort
      - run: cat ${GITHUB_EVENT_PATH}
      - uses: googleapis/release-please-action@v4
        id: release_please