name: paths filter runner

on:
  workflow_call:
    inputs:
      filters:
        description: ''
        default: filters.yaml
        required: false
        type: string
      filters_cmd:
        description: ''
        required: false
        type: string
      release_please_manifest:
        description: ''
        required: false
        default: ${{ vars.release_please_manifest }}
        type: string
    outputs:
      changes:
        description: ''
        value: ${{ jobs.runner.outputs.changes }}

jobs:
  runner:
    runs-on: ubuntu-latest
    steps:
      - run: env | sort
      - run: cat ${GITHUB_EVENT_PATH}
      - uses: actions/checkout@v4

      # Generate filters ######################################################
      - run: jq -r 'keys | reduce .[] as $i ({}; .[$i] = $i+"/**")' ${{ inputs.release_please_manifest }} > ${{ inputs.filters }}
        if: hashFiles(inputs.release_please_manifest)
      - run: ${{ inputs.filters_cmd }} > ${{ inputs.filters }}
        if: inputs.filters_cmd

      # Paths-filter action ###################################################
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: ${{ inputs.filters }}
    outputs:
      changes: ${{ steps.filter.outputs.changes }}
