name: performance tester

on:
  workflow_call:
    inputs:
      host:
        description: ''
        required: true
        type: string
      performance_test_file:
        description: ''
        required: false
        default: ${{ vars.performance_test_file }}
        type: string
      performance_test_timeout:
        description: ''
        required: false
        default: ${{ vars.performance_test_timeout }}
        type: string


jobs:
  tester:
    timeout-minutes: ${{ inputs.performance_test_timeout }}
    runs-on: ubuntu-latest
    steps:
      - run: env | sort
      - run: cat ${GITHUB_EVENT_PATH}
      - uses: actions/checkout@v6

      # Execute K6 performance test file ######################################
      - uses: grafana/k6-action@v0.2.0
        if: hashFiles(inputs.performance_test_file)
        with:
          filename: ${{ inputs.performance_test_file }}
        env:
          HOST: ${{ inputs.host }}
          SCHEMA: https